---
- name: deploy
  hosts: server

  tasks:
    - name: Create heimdall service directory
      file:
        path: "{{ ansible_user_dir }}/heimdall"
        state: directory
    - name: Copy heimdall docker-compose file
      copy:
        src: services/heimdall/docker-compose.yml
        dest: "{{ ansible_user_dir }}/heimdall/docker-compose.yml"
    - name: Start heimdall service
      command:
        chdir: "{{ ansible_user_dir }}/heimdall"
        cmd: docker compose up -d

    - name: Create kiwix service directory
      file:
        path: "{{ ansible_user_dir }}/kiwix"
        state: directory
    - name: Copy kiwix docker-compose file
      copy:
        src: services/kiwix/docker-compose.yml
        dest: "{{ ansible_user_dir }}/kiwix/docker-compose.yml"
    - name: Start kiwix service
      command:
        chdir: "{{ ansible_user_dir }}/kiwix"
        cmd: docker compose up -d

    - name: Create filebrowser service directory
      file:
        path: "{{ ansible_user_dir }}/filebrowser"
        state: directory
    - name: Copy filebrowser docker-compose file
      copy:
        src: services/filebrowser/docker-compose.yml
        dest: "{{ ansible_user_dir }}/filebrowser/docker-compose.yml"
    - name: Create filebrowser.db
      file:
        path: "{{ ansible_user_dir }}/filebrowser/filebrowser.db"
        state: touch
    - name: Copy filebrowser json configuration file
      copy:
        src: services/filebrowser/.filebrowser.json
        dest: "{{ ansible_user_dir }}/filebrowser/.filebrowser.json"
    - name: Start filebrowser service
      command:
        chdir: "{{ ansible_user_dir }}/filebrowser"
        cmd: docker compose up -d

    - name: Create archivebox service directory
      file:
        path: "{{ ansible_user_dir }}/archivebox"
        state: directory
    - name: Copy archivebox docker-compose file
      copy:
        src: services/archivebox/docker-compose.yml
        dest: "{{ ansible_user_dir }}/archivebox/docker-compose.yml"
    - name: Start archivebox service
      command:
        chdir: "{{ ansible_user_dir }}/archivebox"
        cmd: docker compose up -d

    - name: Create wallabag service directory
      file:
        path: "{{ ansible_user_dir }}/wallabag"
        state: directory
    - name: Copy wallabag docker-compose file
      copy:
        src: services/wallabag/docker-compose.yml
        dest: "{{ ansible_user_dir }}/wallabag/docker-compose.yml"
    - name: Start wallabag service
      command:
        chdir: "{{ ansible_user_dir }}/wallabag"
        cmd: docker compose up -d

    - name: Create gitea service directory
      file:
        path: "{{ ansible_user_dir }}/gitea"
        state: directory

    - name: Copy gitea docker-compose file
      copy:
        src: services/gitea/docker-compose.yml
        dest: "{{ ansible_user_dir }}/gitea/docker-compose.yml"

    - name: Start gitea service
      command:
        chdir: "{{ ansible_user_dir }}/gitea"
        cmd: docker compose up -d

    - name: Install Caddy
      become: true
      shell:
        cmd: |
          apt install -y debian-keyring debian-archive-keyring apt-transport-https &&
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg &&
          curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list &&
          apt update &&
          apt install caddy
    - name: Copy Caddyfile
      copy:
        src: Caddyfile
        dest: "{{ ansible_user_dir }}/Caddyfile"
    - name: Start caddy
      become: true
      command:
        cmd: caddy reload
