---
- name: Provision
  hosts: servers

  tasks:
    - name: Update repositories and upgrade packages
      become: true
      apt:
        update_cache: yes
        name: "*"
        state: latest

  roles:
    - sshd
