---
- name: Provision
  hosts: server
  gather_facts: false

  pre_tasks:
    - name: Gather needed facts
      setup:
        gather_subset:
          - user_id
    # - name: Print all available facts
      # debug:
        # var: ansible_facts
    - name: Update package index
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - sshd
    - ufw
    - dnsmasq
    - pki
    - nginx
    - docker
