---
- name: Provision
  hosts: server

  pre_tasks:
    - name: Update package index
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - sshd
    - { role: docker, become: true }
