---
# https://grafana.com/docs/grafana-cloud/quickstart/docker-compose-linux/
# https://github.com/prometheus/node_exporter

# docker network inspect <network name>
# https://docs.docker.com/engine/tutorials/networkingcontainers/

services:
  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:7004:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      # The default network is useless now
      - default
      - monitoring

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - node_exporter
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    # network_mode: host
    command:
      - '--path.rootfs=/host'
        # For the Node exporter full grafana dashboard
        # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
        # - '--collector.systemd'
        # - '--collector.processes'
    expose:
      - "9100"
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring

volumes:
  grafana_data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
    external: false
