---
version: '3'

services:
  grafana:
    image: grafana/grafana:9.3.1
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "7009:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - node_exporter
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  node_exporter:
    # image: quay.io/prometheus/node-exporter:latest
    image: prom/node-exporter:v1.5.0
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    # network_mode: host
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'

volumes:
  grafana-data:
  prometheus-data:
