---
- name: Create flame TLS server CSR
  become: true
  shell:
    cmd: |
      SAN=DNS:flame.home \
      openssl req -new \
        -config /etc/pki/tls-server.cnf \
        -out /etc/pki/certs/flame.home.csr \
        -keyout /etc/pki/certs/flame.home.key
    stdin: |
      flame.home
      Home
    creates: /etc/pki/certs/flame.home.csr
- name: Create flame TLS server certificate
  become: true
  command:
    cmd: >
      openssl ca
        -batch
        -config /etc/pki/signing-ca.cnf
        -in /etc/pki/certs/flame.home.csr
        -out /etc/pki/certs/flame.home.crt
        -extensions tls_ext
    creates: /etc/pki/certs/flame.home.crt
