---

version: '3.6'

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    # Doesn't work, database is not readable
    # user: '65534:65534' # nobody
    volumes:
      - data:/data
    ports:
      - '127.0.0.1:7005:80'
    environment:
      DOMAIN: "https://vaultwarden.home"

volumes:
  data:
