---

version: '3.6'

services:
  flame:
    container_name: flame
    image: pawelmalak/flame:2.3.1
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - '127.0.0.1:7000:5005'
    environment:
      - PASSWORD_FILE=/run/secrets/password
    secrets:
      - password

secrets:
  password:
    file: ./password.secret
