---
version: "3.8"

services:
  app:
    image: kiwix/kiwix-serve:3.4.0
    restart: unless-stopped
    command: --library library.xml
    ports:
      - "7002:80"
    volumes:
      - /mnt/data/kiwix:/data:ro
