---
version: "3"

services:
  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - gitea:/data
      - ./app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
    ports:
      - "127.0.0.1:7011:3000"
      - "127.0.0.1:7012:22"
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - gitea

volumes:
  gitea:
  db:

networks:
  gitea:
    external: false
