---
services:
  server:
    image: codeberg.org/forgejo/forgejo:1.20
    container_name: forgejo
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - forgejo
    ports:
      - "127.0.0.1:7007:3000"
      - "127.0.0.1:7008:22"
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    user: "70:70" # postgres
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - forgejo

volumes:
  forgejo:
  db:

networks:
  forgejo:
    external: false
