---
- name: Create docker cli plugins directory
  become: true
  file:
    path: "{{ docker_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Check docker-compose version
  command: docker compose version
  register: check_docker_compose_version
  ignore_errors: true
  changed_when: false

# Downloads the docker-compose binary if no version of docker-compose is
# installed or if the wrong version is installed
- name: Download docker-compose binary
  become: true
  get_url:
    url: "{{ docker_compose_binary_url }}"
    dest: "{{ docker_plugins_dir }}/docker-compose"
    owner: root
    group: root
    mode: '0755'
  when: (check_docker_compose_version.rc != 0
    or not check_docker_compose_version.stdout.endswith(docker_compose_version))
