---
version: "3.8"

services:
  heimdall:
    image: linuxserver/heimdall:2.5.4
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
    ports:
      # - "127.0.0.1:7000:80"
      - "7000:80"
      # - "443:443"
