---
- name: Install dnsmasq
  become: true
  apt:
    update_cache: yes
    pkg: dnsmasq

- name: Configure dnsmasq
  block:
    - name: Copy configuration
      become: true
      copy:
        src: "dnsmasq.conf"
        dest: "/etc/dnsmasq.conf"
        owner: root
        group: root
        mode: '0444'  # No Owner write permission, let's try to be stateless

    - name: Generate dnsmasq-hosts.conf
      become: true
      template:
        src: "dnsmasq-hosts.conf.j2"
        dest: /etc/dnsmasq-hosts.conf
        owner: root
        group: root
        mode: '0444'
  notify: Restart dnsmasq service

- name: Prevent dhclient from updating resolv.conf
  become: true
  copy:
    content: |
      #!/bin/sh

      # https://wiki.debian.org/resolv.conf
      make_resolv_conf() {
          :
      }
    dest: /etc/dhcp/dhclient-enter-hooks.d/no_update_resolv_conf
    owner: root
    group: root
    mode: '0544'

- name: Configure resolv.conf to use dnsmasq DNS
  become: true
  copy:
    content: |
      nameserver ::1
      nameserver 127.0.0.1
      options edns0
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0444'

- name: Enable dnsmasq
  become: true
  service:
    name: dnsmasq
    enabled: true
