---
- name: Install packages to allow to use a repository over HTTPS
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker official GPG key
  shell: >
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get docker repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  register: get_docker_repository

- name: Add docker repository
  apt_repository:
    repo: "{{ get_docker_repository.stdout }}"
    state: present

- name: Install docker
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
