---
- name: Install packages to allow to use a repository over HTTPS
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker official GPG key
  become: true
  shell:
    cmd: >
      curl -fsSL https://download.docker.com/linux/debian/gpg |
      sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get docker repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] {{ docker_repo_url }} stable"
  register: get_docker_repo
  changed_when: false

- name: Add docker repository
  become: true
  apt_repository:
    repo: "{{ get_docker_repo.stdout }}"
    state: present

- name: Install docker
  become: true
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Create docker cli plugins directory
  become: true
  file:
    path: "{{ docker_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Check docker-compose version
  command: docker compose version
  register: check_docker_compose_version
  ignore_errors: true
  changed_when: false

# Downloads the docker-compose binary if no version of docker-compose is
# installed or if the wrong version is installed
- name: Download docker-compose binary
  become: true
  get_url:
    url: "{{ docker_compose_binary_url }}"
    dest: "{{ docker_plugins_dir }}/docker-compose"
    owner: root
    group: root
    mode: '0755'
  when: (check_docker_compose_version.rc != 0
    or not check_docker_compose_version.stdout.endswith(docker_compose_version))

- name: Enable and restart docker daemon
  become: true
  service:
    name: docker
    enabled: true
    state: restarted
