---
- name: Install packages to allow to use a reposotory over HTTPS
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker official GPG key
  shell: >
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install docker
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
