---
- name: Install packages to allow to use a repository over HTTPS
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker official GPG key
  become: true
  shell:
    cmd: >
      curl -fsSL https://download.docker.com/linux/debian/gpg |
      sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Get docker repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
  register: get_docker_repo
  changed_when: false

- name: Add docker repository
  become: true
  apt_repository:
    repo: "{{ get_docker_repo.stdout }}"
    filename: docker
    state: present

- name: Install docker
  become: true
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Enable and start docker daemon
  become: true
  service:
    name: docker
    enabled: true
    state: started
