---
- name: Install package to verify release signature
  become: true
  apt:
    update_cache: yes
    pkg: minisign

- name: Download 2.1.5 release
  become: true
  get_url:
    url: https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/2.1.5/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz
    dest: /tmp/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz
    owner: root
    group: root
    mode: '0444'

# We pin the signature
- name: Copy 2.1.5 release signature
  become: true
  copy:
    content: |
      untrusted comment: signature from minisign secret key
      RUTk1xXqcTODeciu1DEzQ2tpBPEXRlQVb+rr+qGEji9itFT0H99wZNqARj7hEuUlUeb30Uf95tW299rwKozLv0qVRFQ3Y7vf7ww=
      trusted comment: timestamp:1691773871	file:dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz	hashed
      XslsI10/7nF4hW21kNSs7bzEJLUN20sRh/YerwiEKXeryJ2rXiAbpmzsSjv0YIKw+z7Q6JnbBVvTEnRZ6NvDCg==
    dest: /tmp/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz.minisig
    owner: root
    group: root
    mode: '0444'

- name: Verify release
  command:
    cmd: minisign -Vm /tmp/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz -P RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5

- name: Extract release
  become: true
  unarchive:
    src: /tmp/dnscrypt-proxy-linux_x86_64-2.1.5.tar.gz
    dest: /tmp
    remote_src: yes
    owner: root
    group: root
    mode: '0555'

- name: Copy binary
  become: true
  copy:
    src: /tmp/linux-x86_64/dnscrypt-proxy
    dest: /usr/local/bin/dnscrypt-proxy
    remote_src: yes
    owner: root
    group: root
    mode: '0555'

- name: Copy systemd socket
  become: true
  copy:
    src: dnscrypt-proxy.socket
    dest: /etc/systemd/system/dnscrypt-proxy.socket
    owner: root
    group: root
    mode: '0444'

- name: Copy systemd unit
  become: true
  copy:
    src: dnscrypt-proxy.service
    dest: /etc/systemd/system/dnscrypt-proxy.service
    owner: root
    group: root
    mode: '0444'

- name: Create configuration directory
  become: true
  file:
    path: /etc/dnscrypt-proxy
    state: directory
    owner: root
    group: root
    mode: '0555'

- name: Copy configuration
  become: true
  copy:
    src: dnscrypt-proxy.toml
    dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    owner: root
    group: root
    mode: '0444'
  notify: Restart dnscrypt-proxy

- name: Enable dnscrypt-proxy
  become: true
  service:
    name: dnsmasq
    enabled: true
