---
version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2.23.0
    container_name: filebrowser
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "7003:80"
    volumes:
      - /mnt/data/filebrowser:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
