---
version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:v2.25.0
    container_name: filebrowser
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "127.0.0.1:7002:80"
    volumes:
      - /mnt/data/filebrowser:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
