---
- name: Configure sshd
  become: true
  template:
    src: "sshd_config.j2"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: Create root-owned authorized_keys directory
  become: true
  file:
    path: /etc/ssh/authorized_keys
    owner: root
    group: root
    state: directory
    mode: '0755'
- name: Add music user
  become: true
  user:
    name: music
    create_home: no
    shell: /usr/sbin/nologin
- name: Add music authorized_keys file
  become: true
  file:
    path: /etc/ssh/authorized_keys/music
    state: touch
    mode: '0644'
